function getImg() {
  return require("heatshrink").decompress(atob("2Gwgc8+fPAX1v237AXyD/AQPt33bAXyD/AQL+4ARCD/AQL+4ARCD/AQL+4ARCD/AQL+4ARCD/AQL+4ARCD/AQL+4ARBxv7/9CJ7vn3wFE3u2/4ABDRx9o//8AoM/tu27d/+4ICDRbvnPYQFB/ZBCtu3BAQaLPsP/AoZAC/4FB7d924CC74gNfzxwBAQIICAoJBC23+QAKDC23f/wjMf0KDJ+xBF7d/EZj+e345C/YIBIAaECIIwRDEZKDeHAfP/iJBAAm37d9AQv/EZb+VARA6GQZoVBEZaDdn46FQY3/II/3EZb+VAQ/hy47GAAv7QY4jLQbf/58M+PPIJl92/bAQf/7gmKfyoCF3/7kO2vaEMv/+ZAn/94mKQbX8GIMMuPHj5CM/5BE+/8ExT+UAQnfFwP4sGWrNnIKX/FJaDan6DD58cIJv7vu37d9//cExT+SARH//MhyV7QZv+/aDE94mKQbnDhkx48cv7FQt/3Exb7OBxZwB5Fgw1ZsuW75AK3yDDTgImLO5ghB/gIEAos/+XHhlx58c+PPIBP92/bvoCC/41LfBoABBAYFFAQOyjMhyV7s+2vYLCIAqABOQKDDGRQCBQaYGBBwvw4cMmPHjlx44dEO4Q7BHwQCCv/3GpbRL9u/dAQFE/wODsu2hFgw1JsuWrIgH+xBHGRQCBQZwABAo4OBjnw48MuCDB+IIBEA/bvu3AQf9GRQCBaJdvPoTrBAo22/MjyUZkOSjdn217EBCDF7/2GRQCBQaH//iDG4cMmACCQYNxAQIgHnZBE/9zQZjRL95BEAAoOB5Fgw0IAQMJsuWrNlEBBBD3/9GRQCCJpZAKRIPy48MuACDjnx56DInn92/f/v/WxgCBaJO3G4X4IRO2jMhyQCDs+2vYCBepAXB/wLIAQxNKIIcfIJHy4cMmACDjlxQwL4NARzRJ35BN/0IvmGhFgAQNly1ZAQL4MARxNJG4hBJ+HH//x48MuCAB+PPAQSDaaJO3QZqGDjMhyUZs+2vYCCfZwCLI4nHQY/4h5BL//Dhkw4ccuKGBAQIjCjiDWZYkDAoe/IIcDIJnIsGGhFly1ZAQe+5ACBfxgCII4fyg5NEfYUHIJvHhlwPQPx54CD+SDYZYkDAon/t/wgEP25AK/0ZkOSjMn217s4CDjICBfZAaBBZP7I4fwcwRQE+HAhlzHIXP/iPCAAXw4cMmHDjlxPoICCuAIBuZ3IDQKDKZAPYsuwgDUH4EAnwIF75AC/mGhFgAQNly1ZAQgIC7ImG36eCEwoCDIgUcfwLjGBAMANAvx48MuACH+IgBAQSnBRIJ3HT4anCBwzIB7Mn2EDag2AgAIFtuyjMhyQCGke2vdnAQQLCAoImGQYQACBYoCBNwLgBNAJcGwHAhgIFfwMMARFxPoQIHUIpAEQZHt2zsBy0DtrUFQYMBBAfY8D+BsACHsOWrNly1IBYkZsomEIAgAB/wyEAQL7BdgUHjhQF+EHgBlEfwYCI+PPjnxBYoICDoZBG/6DGt7yC2EAg7UFQYIABnYIBnL+CAREjfwNn2VZBYeQnNnBYIdBIA//GQgCBnmwcYXAcAsMgHAhkBRIT1EARD+CuILGBAILBuZBIQY3hcAR6BguWaIfgQQUOBAO2fwYCJy1ZsmWBAmAhFhBYNl3xBIGQYCCljgDfwLgEPoIIBAob1FAQ9xfwILGg8MEwMcAQJCIQYrgDy0AgbgDagKMBgE25djfwgCJDQNlBAuAAoV5s4OBIJHvGQQCBcAnAcAZcBhkA4EMgfHlj+FARAaCBAsAAoYpBO4ZBF/iDEcAT9CgOWrFly1bBAUAh3DfwwCIfYNkBAuABwtbfwoCB/4IFcAUAcAMA+EPQYQIDuT+HARB0BBxz+FAREgcAMgPYc4g+2vAHDgEIfwwCIOgIIFEwIRFjdnfwgCFsYCBcAj+BcYLgBAoQIDfwwCImIIHDQ8cU4KAIlgCBsEGgFgPIQFBNYNZsuAQgcgeooCJpAIGDQIIGy0bfwQCFkICBbQT+DcAkc+AICBYgCVg4IHQAwCChgCBgB3EAAUny17sYLEgL+FASOABZMtfwNvAQkDAQLXBfwoCBmJcBBAr1FASIaLmKDHufPkECQY0AwwHGkD+GAR4jEBxHblu+7fsn3YkE+7bXCfYjjCaIIIDfyICGEYgOI58cQYVzBAKDBgGALgkAAoOCjCGCgOQBAMSfxoCHkAlCDRUP237TAeG/bgGgDpHdhYCMDQgmFAQqDBlkxAoMz58ggT4BLgUGAoICCRogLBhEgRgL+IAQ4bFBxMhx3bHYPAAQPbcArjHBAT+PARAjHAQ9z58MuIFDkD4BgOALocByRlGBAMZAQMYd5ACGEYwRIjEAAoMAwE4gGG/bgGdKgCLDQYdTQYR5FfwcABYsgBATpBARD4IEYgLDEAIODAocC4Egh0bcArjFBBACTDQYdSuQ1BwEIfw4IFdgUYBYQFCgGCjL4MAAYaDC4UgAoYRBHYWAjL+GagYIIASIaEDqz7FAAbpFwTgBcYQCFdILyEAQYjGgwmDkECC4QdDsECAobgLBAj+OAQwjFEwoaPAAWAAQRlBdgKPGcYLsCd4gUDkICFyAbFC4OQfYUYF4YFGjLmGagrsZEYYaWagLXCLYIFFdIj1BBYOCcAbsGwwCFQYoRBDoQaCF4QaCAojLEfxAIIASIaCDqrLELQIFDBAzyBfwTvByTmBwQICjMhAQoaCAAUSCIIUCFguCjIFFcZMABAjpTAQYgDEYoCPaIbiGAAILBAQTjFd4ICBgwLCdgIIBAQomFC4VgDoICCBAaPBAoTIDcYzpYd4wdWfYYAMcw4CBgL+BAQUhAQinHDpICIfYbjGAQjmQAQwgZLg4AHgT7CARlgd4QCCVQ4dOAQT+HARDpSAQgdYQRwADdKEByQFCDSoCCcBLpZAQgaRF4yDSdKACDDSIvIcAwCLdiYaQF5IAUd6IaPCBL+JARbvMeRICBBxwCDQarvLAQgXMFhz+JARjvIARQUGFh4AXd4wCKgAIFFB7+MARzyDARUAAoQmSNgVp0CGWeooCICAICCACTgEbR4CHfAoCHEasBwEQgEEjSEWAAj7DAQgAWjExwcYsD7NdJwRCAQb+PARFBk0asOEgFBKJAOBsBjOgT+BAQSjZjFxw8YcYQFBfAwID47pOhggCfyACIoOgjVBkkSoBJBJ4sB0EQoOkM6P7keyB5lAkgvFAAcMsDjBsOGhkxAQLUDBYMxwYRBboYhB4wCBdhHHlkw4c8fxcwBZNJwiDBgx3CzEIgEQgMAjVhk2SpMEiEAg2CsILBsEAzB1Jn3YBwIAHkEatMkgVpwANGjD4BAQbpEAQYOFAQL7Cd5wdCBZAvFBYtB0EagOAQYMgjCACgOggSMBSQMkRgOkCIOgCIMkiQaBMgcAeoNAAwMByUbQwodBEwMEjSQHjD1BfYNgeQL+BjAICmOGBAQOB4EYmARBsILBAoLpEC4IICsOAhlzBAT7EBwYdBBAUxCgMw4ZNBNwOEjVJAQNpBANJQANhAQNJw2YoMGyFpwmaoOmiFITAUEzVh02QBYOSNwPb9j7FgggBFgIvCoMmyEJ00Yeor4DBA4CCgAOCdIIIFdILyBCgQFBeQT7HCIICECgQaCfYLvCAQOkiT+BNwL+BOIILCAoIOCgAFBQANBwAIBNYMBwAIBkAOCgEP2S7BAAIIBFgQmBwg1EF4LUDAQj1Bd4YFGmLmBsAUBsALBd4VhwYCDBYT4CDoQFBEYQgBwYdCEwtp0zUCzFhk2apIIC0mQsMEjVJ0gIBgz7CCIOEBYIOBd4OatMGyARCoB+Cn3b9mGgD+BiCYCAQgpBwmYZwzsFAQ7jIAoQdGAQL+Bg4CBFIwCDDQgsCO4LsCcYOEKATXCjDgBd4USgL7CgALBfwUAjUB0DsBeQNB0EYQQQZBjNv20ZCIIsBGoQUBgMkAoIIBbQb4Bd4LXCAoLgCBYL4EwwRBAQQUBAoLsCAopCB4EMufPngjCFIIOBEYIvCsALBBANpd4ICBzACByVha4WmKYMmBwb1BiT+BiFJ0madgQFBTwWaDoMaoEAgdgw3bAQXhFIQCEtOEiQ1CcYrUIeooICdIQFDCg4CCgFx58sAoM8+YgBDQgjGCILRDfwL1BfAJlBeoLgEAQWABwQLB0ESAQIUDDoYCBge2jMh237tuSEAQaBgAaBAoMBkgCBAoL7CfwbpCa4gLDCIrgBfwICBCIodDBANz588+QODhgaCEYgaFeoL4CAQTaEkwIBR4NJCI9pgmQpOEBYoCC7Fh3//9u+7QOHAQ41BdIQCMbQgIFC5cc+f//nyBYwgGAQ74GARLaCBY0BL4LpBBYsbt+2/YCDBYcYEBACFaJACH4zjLBY0x5//+fPngLGCgNhwYmHAoNg4bXP02YCKGafwPb9mGjftBw2QoMmAoUSoMGBwdBw2aaJYCXjiACAQQOHjAFCuOHDowIBZAJNBeoryGASGm/V//37sOW7QXNiALIepDgBboQLHARZ9C///nnyDSYCEa4VpZYLRCsMEfx4CF9u+7YCC9IaTAQrXGAo4CRnnz//8QwQdWAQTIBjFB0DUEkj+NAQu2YAP2AQX7DSQCHZAPGjDgWAQdzPoKAC+ALEsHGEajIBzFBwzjYtOn2ft33aBY2kiVpggCBEaDICjDjZhiAB7d/54LGuOHFKjLDgjjYt+2+////7AoIOFjEBEabXRjExwwLInn923btvOnnyBwvGFiICCfaUEBZPt3+/IIO79ojRART+Ud5E8+fP//95/b+AjSARD+S0ESBY8bt+2/yDB/dv2j+SAQcgAobOGmODbRILImPPQYXbuYFCfyQCE4wFCZw8YpLjSzft33bAQnafyICDwkSAoTgaAQU8/4AD/nwEC1xw4FCag8QoMkdKM7t+2/YCDC58SBA2gAobRIjDmS588+YCE2AXNsHDFhbUHzFJdKWb9u+YYP+7ftC58QpMmBxLgVcwyDHepQIMAQjaHjDpNAQm2/dvAQltBwuEDRESExb7QARUzYQKDElgOFmOGEyj7QARWu7ft3wCEBwpuBEyj4Nw8YBxaAEn6IBnnwfyQCIfZsQgILJndv237AQ20EZYCPahvGhlhdhHHQAU8QAQFC+T+SARDUOpMmBZGb//+7ft3wCE2z+SARDUOjALIuJ6BPoQCF+T+SEAOHBArdXob+CAQ9hEakABAzdW46AI/4CBlgjUsHGBArgYfwW/////wFBBAQgU0kSBArgSAQ6GInnyEbACCcCQCHt+2/YCIEzTgSAQyAH+bLBAoImZ4bgSARG+7ftAQ3aEzQ="))
}
var IMAGEWIDTH = 176;
var IMAGEHEIGHT = 109;

Graphics.prototype.setFontZCOOL = function() {
// Actual height 40 (46 - 7)
var widths = atob("CxAhEh8hJCIjGSMdCw==");
var font = atob("AAAAAAAAAAAAAAAEAAAAAAAPAAAAAAAP4AAAAAAD+AAAAAAA/gAAAAAAP8AAAAAAB/AAAAAAAfAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAfgAAAAAAf4AAAAAA/+AAAAAA//AAAAAB/+AAAAAB/+AAAAAD/8AAAAAD/8AAAAAD/4AAAAAH/4AAAAAH/wAAAAAD/wAAAAAAfwAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAP8AAAAAB//gAAAAP//4AAAB////AAAP////wAAf///h8AAH//8AfAAD//gAHwAA/8AAB8AAPgAAAfAAD4AAAHwAAfAAAB+AAHwAAAPgAB8AAAD4AAfAAAA+AAHwAAAPgAB8AAAD4AAPgAAA+AAD4AAAPgAA+AAAD8AAPgAAAfAAD4AAAHwAA/////8AAH/////AAB/////wAAf////4AAD////8AAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAB8AAAAAAA/AAAAAAAfgAAAAAAH4AAAAAAD8AAAAAAB+AAAAAAA/AAAAAAAPwAAH/gAH4D///4AD/////+AB//////gAf/////4AD////gAAA//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAB8AAAGAAAfAAAD4AAPwAAB/AAH4AAA/wAB8AAAf8AA/AAAP/AAfgAAP/gAHwAAH/4AD8AAD++AB+AAB/PgAfAAA/j4AHwAAfw+AB+AAP4PgAfwAH8D4AD8AH+A+AAfgD/AfAAD8B/AHwAAfg/gB8AAD8fwAfAAA/v4AHwAAH/8AB8AAA/+AAfAAAH/AAHwAAA/AAB8AAAHgAA+AAAAAAAPgAAAAAAD4AAAAAAA+AAAAAAAAAAAAAAABAAAAAAAD4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAAAA+AAAAAAAHwAAMAAAB8AAfAAAAfAAHwAAAHwAB8AAAA+AAfAAAAPgAHwAfAD4AA+AP4A+AAPgD+APgAD4B/gB8AA+A/8AfAAPgf/AHwAD4H/wB8AA+D98AfgAHh+fgD4AB4/D4A+AAffg+A/gAH34Pg/4AB/8D8f8AAf+Aff+AAH/AH/+AAA/wB/+AAAP4Af+AAAD8AD/AAAA+AA/AAAAHgADAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAD+AAAAAAH/gAAAAAH/4AAAAAP/+AAAAAP//gAAAAf/z4AAAAf/w+AAAA//gPgAAA//gD4AAAf/AA+AAAH/AAPgAAB/AAD4AAAeAAA+AAACAAAPgAAAAAAD4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAAAA+AAAAAAAP/+AAAAP///gAB/////4AAf////+AAH/////AAB///+AAAAf/APgAAAAAAD4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAAAAAAAAAAAAACAAAAAAAHwAAAAAAB8AAAAAAAfAAAAAAAH4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAfwA+AAAH/+AHwAAf//gB8AAP//4AfAAH//+AHwAB/+PwB+AAfwB8APgAHwAfAD4AB8AHwA+AAfAB8APgAHwAfAB8AB8AHwAfAAfAB8AHwAHwAfAB8AB8AH4AfAAfAA+AH4AHwAPgH+AB8AD4H/gAfAA+H/wAHwAPv/4AB8AD//4AAfAA//wAAHwAP/wAAB8AD/gAAAAAAfgAAAAAABAAAAAAAAAAAAAAAAAHwAAAAAAH8AAAAAAD/gAAAAAD/4AAAAAD/+AAAAAD/3wAAAAD/x8AAAAD/4PgAAAD/4D4AAAD/4A+AAAB/4AHwAAB/4AB8AAB/4AAfAAB/4CAD4AB/8DgA+AAf8B8APgAD8AfAB8AA8AH4AfAAEAA+AH4AAAAPgA+AAAAD8AfgAAAAfAP4AAAAH4P8AAAAA+H+AAAAAPj+AAAAAB9/AAAAAAf/gAAAAAH/wAAAAAA/4AAAAAAP8AAAAAAB8AAAAAAAOAAAAAAAAAAAAAAAAAAAAD4AAAAAAA+AAAAAAAPwAAAAAAB8AAAAAAAfAAAAAAAHwAAAAAAB8AAAAAAAfAAAAAAAHwAAADAAB8AAAD4AAfAAAD+AAHwAAH/wAB8AAH/4AAfgAH/4AAH4AH/4AAA+AH/wAAAPgH/wAAAD4H/wAAAA+H/wAAAAPv/wAAAAD//wAAAAA//gAAAAAP/gAAAAAD/gAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAH4AAAAAAB+AAAHwAA/wAAB8AAf8AAA/gAP/AAAP8AH/wAAH/gD8+AAB/4B+PgAAf/A/j4AAPn4Pw+AAD4/H4HwAB+Pz8B8AAfB/+AfAAPwP/AHwAD4B/gB+AA+AfwAPgAfAP+AD4AHwD/wA+AB+B/+AfgAfw/PgPwAB/fj8D8AAP/wfh+AAB/4D8fAAAP+AfPwAAB/AH/4AAAPgA/8AAAAAAH/AAAAAAA/gAAAAAAPwAAAAAAB8AAAAAAAAAAAAAAAAAAAAAGAAAAAAAD4AAAAAAB/AAAAAAB/wAAAAAA/+AAAAAAf/gAAAAAf78AAAAAP8fAAAAAP+H4AAAAD+A+AAAAB/APgAAAAfAB8AAAAH4AfAAYAA+AD4AfAAPgA+AfwAD4APgf+AA+ABgf/AAHwAA//AAB8AA//AAAfAA//AAAHwA//AAAB+A/+AAAAPh/+AAAAD5/+AAAAA//+AAAAAP/+AAAAAB/8AAAAAAf8AAAAAAH8AAAAAAAAAAAAAAAAADgAOAAAAH4AfgAAAD+AP4AAAA/wD/AAAAH8AfwAAAB/AH8AAAAfwB/AAAADgAOAAAAAAAAAAAAAAAAA=");
var scale = 1; // size multiplier for this font
g.setFontCustom(font, 46, widths, 50+(scale<<8)+(1<<16));
};

// timeout used to update every minute
var drawTimeout;

// schedule a draw for the next minute
function queueDraw() {
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = setTimeout(function() {
    drawTimeout = undefined;
    draw();
  }, 60000 - (Date.now() % 60000));
}


function draw() {
  var x = g.getWidth()/2;
  var y = 24+20;

  g.reset().clearRect(0,24,g.getWidth(),g.getHeight()-IMAGEHEIGHT);
    g.drawImage(getImg(),0,0);

  // work out locale-friendly date/time
  var date = new Date();
  var timeStr = require("locale").time(date,1);
  var dateStr = require("locale").date(date).toUpperCase();
  var dowStr = require("locale").dow(date).toUpperCase();
  // draw time
  g.setFontAlign(0,0).setFont("ZCOOL");
  g.drawString('reindeer',x,y);
  // draw date
  y += 35;
  g.setFontAlign(0,0,1).setFont("6x8");
  g.drawString(dateStr,g.getWidth()-8,g.getHeight()/2);
  // draw the day of the week
  g.setFontAlign(0,0,3).setFont("6x8");
  g.drawString(dowStr,8,g.getHeight()/2);
  // queue draw in one minute
  queueDraw();
}

// Clear the screen once, at startup
g.setTheme({bg:"#f0f",fg:"#000",dark:true}).clear();
// draw immediately at first, queue update
draw();
// Stop updates when LCD is off, restart when on
Bangle.on('lcdPower',on=>{
  if (on) {
    draw(); // draw immediately, queue redraw
  } else { // stop draw timer
    if (drawTimeout) clearTimeout(drawTimeout);
    drawTimeout = undefined;
  }
});
// Show launcher when middle button pressed
Bangle.setUI("clock");
// Load widgets
Bangle.loadWidgets();
Bangle.drawWidgets();
