function getImg() {
  return require("heatshrink").decompress(atob("2FtwcCjlx48c+ffnoCfnnx/89+IpBuIaS7fwnHD/4AixO/9/+nnj9//8YZQQYUd+/PvgCJ74LKARR9BviDBzlx59+u4mGvosH/fwkCCj/+Nn///0g/fPQaUeQYT+ZARE8+P/nqDBWAPfn1zDR/T+U+LgKDixE/9/+nnz96DSKwJZBdgzUDAo4CQEwN8QYfPnl3CI19DQ/7/yDBAEeP06qBkH/56DSj9x88dfzICIVQU9QYffj1zDR/T+E/QcmIm/v/0w/aDTjyDBjjXF+fHbQ/ffxICIQYN8QYfPjl3CIwsBEwvf/eIQY+ORjgdC/0g76DV48d+LpFfyQCIDoPHnqDD78euYaP7eALgRIB/084aAaEAPvEwPv/0wzfv/8DDiGcLgMcuZcCRIL7RARYgBviDCQAMeu4RF74CCvoIBAQPf/2OnHgh0A8eOnaCaAAeIVQUA/+P/HbDKB9CAQn/agsdcZfxBZIjCBwPHj9z58eQwIgJAQnjxk88eAnHjJ438QCv+//vwE/9/+mGT5/4+aDWd5H8fZfxBZQjCQYMeu4sBu4UI799AQfP8ePQAOPNhQAM34JI88On4cBgAHB8CgRQATdBahHHjrjL+P/BA/fngmBAoKDBuYgNAQnj5E4/b8VSIR3BTQ4mBn/v+Eg/f+nyDUzlxbRHH7j4IBwgLInl9BYKDBFgUcCI99AQ/zhk/QZXOQZsnBRHghyPB3EA/+L/iDUj95d4/zcxz7BBY4mD+OHAoQgNAQfjx08QZQAN/x3BAAnv/3/gYFByf/k/yv++EqN8KwMevLvI4+ccw4OFBZB9BQwN5++cFI7+B74FB74FCAQX/x88MYJPI7iDNmwJH/Hgh6KC34DBAQQAPniDCuPnbo7mN+VHBA3xQANx/4CB88f+PHDpICH9+An3jLgZ1GQZs/ToYTBAoP4geAnMDwIRDQaN8KwJcBfwN3fA2dfA4OF/gIFTYIjCAQj+CCIb+BAQXfAQnPKwMA+fv3hPH4iDNnAIHpHghU48UOgn/FwIARfYTgDcwLvE48dcZfyg+dBAqnEAQUeQYIdJAQ5fB/cDt+/6f8cAn+43zKwnvfYIOEnhmG+E5geAnGDAQIdFABzUCnhcBzwCBjr4E7j4FAQ3HzgIFQAgCDu4XFfwXfAooCBbAmInx1B/B0Eg37Lpf+mAHF8EOnHihEw4UInCCTfw0f+PncYILBOgOfcZfxo+dBAYdBQY8dDpYCHIwn4gf/3jjB350Bk3z/yOBAQqDDOgn5n/7/s4wfAmEChE/QajyFjlh+5iC7gCBfAwCFPoPdDQV9CgKDGDRHfAot9BAaDFAAOAn37588+dOgCJBABX+kAOB/AGBn3z90AAAVnQKgABeQ/HjxlDw+ccZYUD88fC4IaE54OBfxgCII4r1B/ED9844eAQYP+BYICH//xPoPsAQPP//74E5t4RFACbaIdIjyBu7sIAQKDBCgd9QAYODBYIsIvoCBAooCCJZOAnnzhEA/aNBABO+mH790gPYOgw4LC3/48EAg6DUZYsdAQRxEeQL+CBYQCDn4RBj15CIXHCIIaCo8ADQT+KARBECOwbjC/34gfImEbeoLvCAQ2OnySBnkDCIMjwEAAAUDQKgABa4fzPobRCQYoIB588d4tx8+cQYIUCAQPBAoWcu4UEEwICFF4QCFIofyMQcAx//8EP0GD98///eAQO/LonPQ4X4DYiAYAATLD+MHNAlHnlx+4FB88cuAOF58+BYKSBQYvHj/x/8ffxoCIIgXvwE4wfPn/7//4geAn/DRIPjwEgweMCIIFBgft/4UBPoOAmEAh6BZAALaDoJlDz95QAQICfYJ3G4EcvPnz15BYl/8/cAQP8FIQCBfYoIBAoYCFIgX9x8kJovghkA/dPn///kk4eJ3H4h08/fP337/EggEIkCBbAALICMoTvCz7pBd4dx++eQY0HRgP3BwMHCgd5/4CB57+OARBEC9uPn7vB/hODwM4gf9n/jwEggeIg+DAoPz/u//YLCgCVBAAX+AogATbQV8dIYCBvvH/lx877CjlhQYvGAoYLE/wODEwIpCAQL+IARBFDx4DC/ngp/4//NmkCh/4+D4B4cOkHChkAgfPn/ggEAwUN359XAArICnh6BfwRrC7wIBiBuDAQsHAQPnjAID++f+P/AQL+PARCDH//ih4DB9O44UAnB2BgECgEwgeAQYNPnGChE0wfPQTv/bocBPoN9d4l5QBACEBwt5+//v/3/omCAQz+GARBFDxOw//vnHgh7vB9/0waBCAAPgpkA+EAnmCpuA/dv2nip6DeZYfx48fd4meOgb+C48QRJPnj15/8fEAMdfyACIIgXv2E/AoX7x4CB/k8foM+gcImHDgE4geAknD9k+6ft3/zDYX+EAYAXbQZiB7198+cvPnOIPGPQ6DKvokBTYImCeQQFBfxICIIof+nwEDp/+8UMgHAgAABp0w8QEB/cOnHz90w+dvDQYAdZYnHj/5/5uB+4CBw4CBg4FHQYcfAQf/z/xfyQCI95GD/GT/8/8YGB8dAkmDPoMDgEgweAkEAh8k7f+nnT/k+6aDfcAQCCOId/+/cfxICDjz+BjgCCv///ogBfyICII4vipsA7YFB+EIgHDp84/8MkHzh048eN3AQB/37UQgAdZYs8d4V5/56GuPnzgID88fAQKGBbwP5EYwCX9/+/4CD9DvD8eAkkDwEAgfgkGb/E+geJ//7HoPzQUP/vjjBAQV9+LvC+6DDgPAAoPEPoKDCBwWHz1/dIYjGfxoCIJhX4/eIkHTQYMAh0A4UOkHgh82/+IgCGBAEMdZAICCnvxdgKGCPQVwg8APQIIDAQkfMQL+XARHv/3/AQQAD/U4gfIAQOAnCEBAAUggUMn3/wEHQUX/cYt8/oCBO4tB4CAIzgCB/l374gEAoT+PARBLJwEAgT+ByYFBAAUD50g8eP33yBAKDjjvx78dZYM+uPfOgUYPo4CE84FCj1zfzACI9/+/4CCAAXjwE4gEInED/04BAUCgAFB98//f/3/zQcTmEAQN5559KAQ954/cu/fEAwCBfxwCIJA3v/GAhkgwEIgD+B/CDBgEDgEg+fv3CAjAAUd+PfAQUf+KAQAQMevPnz1zfzACI9/+P4ICB/f+kD7BmACCweOn3DxEggeAnnD/08yZfB/aDicYpxB4yDRjl948fcwIdBARHPfxYCIJA2IgEAh0A8EIgHjx048UIkHih0w8fPQANv/iCi/8d+PfAQR9OiAFEj1x88fd5P/fxwCI9/+/4CC/+AfYcCgE44fMnGDwE4geMnHj/8+GgM+7aDinnz588+/H/iDNAQd5AocdfYl8d4fHfxwCI/+//YCB//kgAABhkgwEAkHzx0w8UIBAMOnHz9/8/fv3yGBAEMd+Pfjvz85uBw8YQx/njwCCubvI87+OAQs/AQPv/3/95HBgUAfYOInmCAoPj5gIBwEwBYM/8f//2T98+waDinnz588cYJ9NAQl/AQN5QYN3dIXPAQnHfxwCFvggB/+//ZtB4GAgAABh0gRIMw+eOQwOOgHDLIPgv///fv3CCi/8d+PfAQKAPj9x/4FB/+cuPnj7yJ/7+NBwYFBAQNz//v/wCB2D4BwD+BpACBAoPD5k8wfOnAfB/ALBn5eB35qKBwQAVnnz588QBoCE4AFC/4CB/rsD598fyACIv4CBM4P78EIgGAhEgwUOAQMMmHjx4CBhBuBx0AgEImycBQZYLLABkd+PPiB3EjCDMg4FCj/x87sCjr7F+L4DAQr+BBYQODBAUfAQPv/z+CkEDhAFBxAICnGD5k8weOn/jwE8BYM06b7ZABc8PRgCNvPH/v357yG+L+MAREdAQPgeILyBgGCgEgwUOkHChEgwcOnHzv/4CgXjx0g8V/fbAALgB9SCgNwg4IE88dd4jyD+LSBBAoFDCgQOCAQYgCgR9BAQT1BnEDxD7Bhk4wfMnnD/04QQM80YRB8Fvn6Ag74CBfyQCCgIFEvPH/oiBd4nPvgOBfxYCIjoCBNwIAD4EIkHjhkwwUMgHCh88+fP/ARC8eOlEDh++NhPvQSn4AYSDUgAIFvP3vr+BfYQCCn1x+71CfxACB78/+ICBAoMdBYMCgEgAQMAAQM4geInGDAQc+CYKDCBwOAnHiv8/f7AAKQafnBA158/9NALvFvl387+LAQf5AoedAQLyCAAWAhkgwUOmHCAoPDh00/ZYD9HixyAj/wDCjCDQjyDHj/5fYPxeQb+B788ub+F/4LBBAvfDQnnjqkBA="));
}
var IMAGEWIDTH = 176;
var IMAGEHEIGHT = 109;

Graphics.prototype.setFontZCOOL = function() {
// Actual height 40 (46 - 7)
var widths = atob("CxAhEh8hJCIjGSMdCw==");
var font = atob("AAAAAAAAAAAAAAAEAAAAAAAPAAAAAAAP4AAAAAAD+AAAAAAA/gAAAAAAP8AAAAAAB/AAAAAAAfAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAfgAAAAAAf4AAAAAA/+AAAAAA//AAAAAB/+AAAAAB/+AAAAAD/8AAAAAD/8AAAAAD/4AAAAAH/4AAAAAH/wAAAAAD/wAAAAAAfwAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAP8AAAAAB//gAAAAP//4AAAB////AAAP////wAAf///h8AAH//8AfAAD//gAHwAA/8AAB8AAPgAAAfAAD4AAAHwAAfAAAB+AAHwAAAPgAB8AAAD4AAfAAAA+AAHwAAAPgAB8AAAD4AAPgAAA+AAD4AAAPgAA+AAAD8AAPgAAAfAAD4AAAHwAA/////8AAH/////AAB/////wAAf////4AAD////8AAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAB8AAAAAAA/AAAAAAAfgAAAAAAH4AAAAAAD8AAAAAAB+AAAAAAA/AAAAAAAPwAAH/gAH4D///4AD/////+AB//////gAf/////4AD////gAAA//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAB8AAAGAAAfAAAD4AAPwAAB/AAH4AAA/wAB8AAAf8AA/AAAP/AAfgAAP/gAHwAAH/4AD8AAD++AB+AAB/PgAfAAA/j4AHwAAfw+AB+AAP4PgAfwAH8D4AD8AH+A+AAfgD/AfAAD8B/AHwAAfg/gB8AAD8fwAfAAA/v4AHwAAH/8AB8AAA/+AAfAAAH/AAHwAAA/AAB8AAAHgAA+AAAAAAAPgAAAAAAD4AAAAAAA+AAAAAAAAAAAAAAABAAAAAAAD4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAAAA+AAAAAAAHwAAMAAAB8AAfAAAAfAAHwAAAHwAB8AAAA+AAfAAAAPgAHwAfAD4AA+AP4A+AAPgD+APgAD4B/gB8AA+A/8AfAAPgf/AHwAD4H/wB8AA+D98AfgAHh+fgD4AB4/D4A+AAffg+A/gAH34Pg/4AB/8D8f8AAf+Aff+AAH/AH/+AAA/wB/+AAAP4Af+AAAD8AD/AAAA+AA/AAAAHgADAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAD+AAAAAAH/gAAAAAH/4AAAAAP/+AAAAAP//gAAAAf/z4AAAAf/w+AAAA//gPgAAA//gD4AAAf/AA+AAAH/AAPgAAB/AAD4AAAeAAA+AAACAAAPgAAAAAAD4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAAAA+AAAAAAAP/+AAAAP///gAB/////4AAf////+AAH/////AAB///+AAAAf/APgAAAAAAD4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAAAAAAAAAAAAACAAAAAAAHwAAAAAAB8AAAAAAAfAAAAAAAH4AAAAAAA+AAAAAAAPgAAAAAAD4AAAAfwA+AAAH/+AHwAAf//gB8AAP//4AfAAH//+AHwAB/+PwB+AAfwB8APgAHwAfAD4AB8AHwA+AAfAB8APgAHwAfAB8AB8AHwAfAAfAB8AHwAHwAfAB8AB8AH4AfAAfAA+AH4AHwAPgH+AB8AD4H/gAfAA+H/wAHwAPv/4AB8AD//4AAfAA//wAAHwAP/wAAB8AD/gAAAAAAfgAAAAAABAAAAAAAAAAAAAAAAAHwAAAAAAH8AAAAAAD/gAAAAAD/4AAAAAD/+AAAAAD/3wAAAAD/x8AAAAD/4PgAAAD/4D4AAAD/4A+AAAB/4AHwAAB/4AB8AAB/4AAfAAB/4CAD4AB/8DgA+AAf8B8APgAD8AfAB8AA8AH4AfAAEAA+AH4AAAAPgA+AAAAD8AfgAAAAfAP4AAAAH4P8AAAAA+H+AAAAAPj+AAAAAB9/AAAAAAf/gAAAAAH/wAAAAAA/4AAAAAAP8AAAAAAB8AAAAAAAOAAAAAAAAAAAAAAAAAAAAD4AAAAAAA+AAAAAAAPwAAAAAAB8AAAAAAAfAAAAAAAHwAAAAAAB8AAAAAAAfAAAAAAAHwAAADAAB8AAAD4AAfAAAD+AAHwAAH/wAB8AAH/4AAfgAH/4AAH4AH/4AAA+AH/wAAAPgH/wAAAD4H/wAAAA+H/wAAAAPv/wAAAAD//wAAAAA//gAAAAAP/gAAAAAD/gAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAH4AAAAAAB+AAAHwAA/wAAB8AAf8AAA/gAP/AAAP8AH/wAAH/gD8+AAB/4B+PgAAf/A/j4AAPn4Pw+AAD4/H4HwAB+Pz8B8AAfB/+AfAAPwP/AHwAD4B/gB+AA+AfwAPgAfAP+AD4AHwD/wA+AB+B/+AfgAfw/PgPwAB/fj8D8AAP/wfh+AAB/4D8fAAAP+AfPwAAB/AH/4AAAPgA/8AAAAAAH/AAAAAAA/gAAAAAAPwAAAAAAB8AAAAAAAAAAAAAAAAAAAAAGAAAAAAAD4AAAAAAB/AAAAAAB/wAAAAAA/+AAAAAAf/gAAAAAf78AAAAAP8fAAAAAP+H4AAAAD+A+AAAAB/APgAAAAfAB8AAAAH4AfAAYAA+AD4AfAAPgA+AfwAD4APgf+AA+ABgf/AAHwAA//AAB8AA//AAAfAA//AAAHwA//AAAB+A/+AAAAPh/+AAAAD5/+AAAAA//+AAAAAP/+AAAAAB/8AAAAAAf8AAAAAAH8AAAAAAAAAAAAAAAAADgAOAAAAH4AfgAAAD+AP4AAAA/wD/AAAAH8AfwAAAB/AH8AAAAfwB/AAAADgAOAAAAAAAAAAAAAAAAA=");
var scale = 1; // size multiplier for this font
g.setFontCustom(font, 46, widths, 50+(scale<<8)+(1<<16));
};

// timeout used to update every minute
var drawTimeout;

// schedule a draw for the next minute
function queueDraw() {
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = setTimeout(function() {
    drawTimeout = undefined;
    draw();
  }, 60000 - (Date.now() % 60000));
}


function draw() {
  var x = g.getWidth()/2;
  var y = 24+20;

  g.reset().clearRect(0,24,g.getWidth(),g.getHeight()-IMAGEHEIGHT);
  if (g.getWidth() == IMAGEWIDTH)
    g.drawImage(getImg(),0,g.getHeight()-IMAGEHEIGHT);
  else {
    let scale = g.getWidth()/IMAGEWIDTH;
    y *= scale;
    g.drawImage(getImg(),0,g.getHeight()-IMAGEHEIGHT*scale,{scale:scale});
  }
  // work out locale-friendly date/time
  var date = new Date();
  var timeStr = require("locale").time(date,1);
  var dateStr = require("locale").date(date).toUpperCase();
  var dowStr = require("locale").dow(date).toUpperCase();
  // draw time
  g.setFontAlign(0,0).setFont("ZCOOL");
  g.drawString(timeStr,x,y);
  // draw date
  y += 35;
  g.setFontAlign(0,0,1).setFont("6x8");
  g.drawString(dateStr,g.getWidth()-8,g.getHeight()/2);
  // draw the day of the week
  g.setFontAlign(0,0,3).setFont("6x8");
  g.drawString(dowStr,8,g.getHeight()/2);
  // queue draw in one minute
  queueDraw();
}

// Clear the screen once, at startup
g.setTheme({bg:"#f0f",fg:"#fff",dark:true}).clear();
// draw immediately at first, queue update
draw();
// Stop updates when LCD is off, restart when on
Bangle.on('lcdPower',on=>{
  if (on) {
    draw(); // draw immediately, queue redraw
  } else { // stop draw timer
    if (drawTimeout) clearTimeout(drawTimeout);
    drawTimeout = undefined;
  }
});
// Show launcher when middle button pressed
Bangle.setUI("clock");
// Load widgets
Bangle.loadWidgets();
Bangle.drawWidgets();
